palomachain/pigeon

Dockerfile
- https://github.com/palomachain/paloma/issues/85
An initial dockerfile for paloma. It supports local-dev (which is still in TODO phase),  and local-testnet modes of work.
=> Initial dockerfile

.air.toml, .gitignore, Dockerfile
- https://github.com/palomachain/paloma/issues/85
Making it easier to work locally. This will trigger a live reload of code.
=> Live reload config

.github/workflows/release.yml, .gitignore, .goreleaser.yaml, Dockerfile
- https://github.com/palomachain/paloma/issues/184
See https://github.com/palomachain/paloma/issues/184
=> Release Go application

app/app.go, chain/evm/client.go, chain/evm/processor.go, go.mod, go.sum, relayer/process.go, relayer/start.go, util/slice/map.go
- https://github.com/palomachain/paloma/issues/192
We need a structured logging library to make it easier to process logs and to get insights into the app.
=> Add logging

README.md
Update the README to refer to Pigeon and not Sparrow.
=> Update conductor to Pigeon

README.md
Fixes https://github.com/palomachain/paloma/issues/311
Clean up the systemd portion of the readme a bit, in particular use an env file for our secrets.
=> Some updates to our systemctl config

README.md
https://github.com/palomachain/paloma/issues/311
Typo.
=> Use `User` in systemd, not `USER`

chain/evm/compass.go, chain/evm/deploy_contract.go, cmd/pigeon/cmd_evm.go, cmd/pigeon/main.go, relayer/start.go, relayer/update_valset.go
- https://github.com/palomachain/paloma/issues/347
A couple of commands to help with signature validation + a bit of a cleaning
=> Debugging commands for verifying signatures

README.md
Update to the 0.5.0 version of pigeon
Update the README for pigeon release 0.5.0
Tested complete and new pigeond version runs. Waiting for rest of chain to catch up.
=> Update pigeon version on README

README.md, cmd/pigeon/cmd_start.go, config.example.yaml, config/config.go, health/interface.go, health/process.go, health/server.go, relayer/keep_alive.go, relayer/process_test.go, relayer/relayer.go, relayer/start.go
We want to stop folks from running paloma chain without them running pigeons. If paloma detects that pigeon is not running, it will kill itself thus stopping a _pigeonless_ validator from entering the valset.
Nope. It does not change anything in the state.
=> Healthcheck

README.md
Update the README 
Update README to point at the latest pigeon binary
Requires palomad working
=> update pigeon README for v0.6.0

relayer/keep_alive.go
It might never send a keepalive.
=> Keepalive hotfix

README.md
Update pigeon to 0.6.1
Solves issues of pigeond dying after keep alive not sent to paloma for the first time.
Test in prod?
=> Update the README for new pigeon releae 0.6.1

chain/evm/compass.go
- https://github.com/palomachain/paloma/issues/476
See https://github.com/palomachain/paloma/issues/476
Not a breaking change.
=> Incorrect argument types when calling a compass-evm logic call function

README.md
README update
README update for Pigeon 0.8.0 file locations
None needed.
=> Pigeon readme update testnet 10 logic call upgrade

chain/evm/client.go, chain/evm/compass.go
- https://github.com/palomachain/paloma/issues/514
Unable to filter logs on bnb endpoint.
=> Unable to filter logs for BNB 

README.md, chain/evm/client.go, chain/evm/client_test.go, chain/evm/deploy_contract.go, config.example.yaml, config/config.go
Update gas price adjustment part
- add txType config
- double gasPrice on EIP-1559 tx(txType == 2) and add gasTipCap
- ignore gasAdjustment if it is less than 1 for safety
- update tests
=> eip-1559 update

chain/evm/deploy_contract.go
=> add logs for constructor parameters

chain/evm/compass.go
=> add more log

chain/evm/compass.go, chain/evm/deploy_contract.go
=> add more logs

relayer/start.go
- Remove `return` in the initial goroutine loop in `Start`
=> refactor: attempt to fix Start loop

chain/evm/client.go, chain/evm/client_test.go, chain/evm/deploy_contract.go, config.example.yaml, config/config.go
=> update for eip-1559

cmd/pigeon/cmd_start.go
N/A
Update greetings from chrrp chrrp to coo! coo! 
N/A.
=> get ready to coo

README.md
=> update README for polygon config

.github/dependabot.yml, .gitignore
- https://github.com/VolumeFi/paloma/issues/6
=> added default dependabot rule

app/app.go, chain/errors.go, chain/evm/client.go, chain/evm/client_test.go, chain/evm/compass.go, chain/evm/compass_test.go, chain/evm/deploy_contract.go, chain/evm/errors.go, chain/evm/health_check_test.go, chain/evm/processor.go, chain/paloma/client.go, chain/paloma/client_test.go, chain/paloma/collision/zero_collision_test.go, chain/paloma/errors.go, chain/paloma/wrappers.go, cmd/pigeon/cmd_keys.go, config/config.go, config/errors.go, errors/unrecoverable.go, go.mod, go.sum, health/background_check.go, health/wait_for_chain_test.go, relayer/build_processors.go, relayer/errors.go, relayer/health_check.go, relayer/health_check_test.go, relayer/keep_alive_test.go, relayer/start.go
- https://github.com/VolumeFi/paloma/issues/5
Fork some unpopular 3rdparty libraries to reduce risk of their removal
=> used forked whoops instead of the original one

.github/workflows/ci-test.yml, .github/workflows/release.yml, chain/evm/compass_test.go
n/a
We've got broken unit tests in master, this is a fix
=> Fix unit test

.github/dependabot.yml, .gitignore, Makefile
n/a
Ease  binary building process, make it similar to Paloma (not 100% similar)
=> added target (Make) to build linux binary

Makefile, scripts/abigen.sh
=> Cosmetic fix

RELEASE_NOTES.md
Release notes for this release
=> Release Notes

relayer/start.go
Already merged in master, but we need it in v1.0.0
- https://github.com/VolumeFi/paloma/issues/193
Pigeon is getting stuck in a lock state because there's a path that on error doesn't unlock.  Now, the locks are closer and don't allow for paths that escape unlocking unless there's a panic
* Tighten the space between locking and unlocking
* Don't bother locking for messages that just query.  These won't affect ordering
=> Fixing locking issue

chain/evm/compass_test.go
Fixes https://github.com/VolumeFi/paloma/issues/38
This function was added but never tested.  Now it's tested
=> Add tests for isArbitraryCallAlreadyExecuted

README.md
Bringing the readme up to date for tomorrow's release in testnet.
=> Update readme for next release

README.md
Brings Readme instructions in master up to date for latest release
=> Updated readme for latest release

go.mod, go.sum
Updating paloma dependency to latest version published today
=> Keep paloma version up to date

.goreleaser.yaml, README.md, chain/evm/processor.go
Merging in additional features/fixes we want in the upcoming release
=> Additional fixes for release

go.mod, go.sum
Keep Paloma version up to date
=> Update paloma to latest

README.md
=> Update README.md added base network

relayer/build_processors.go, relayer/heartbeat/cache.go
[See https://github.com/palomachain/paloma/issues/973
](https://github.com/palomachain/paloma/issues/973#issuecomment-1717727526)
=> fix: remove unnecessary mutex usage

RELEASE_NOTES.md
Reverts palomachain/pigeon#291
Wrong target branch
=> Revert "Add release notes"

go.mod, go.sum, relayer/errors.go, relayer/gravity_batch_relayer.go, relayer/gravity_batch_send_event_handler.go, relayer/gravity_batch_signer.go, relayer/gravity_send_to_paloma_event_handler.go, relayer/message_attester.go, relayer/message_relayer.go, relayer/message_signer.go
Small change to add some more log correlation for processor loop errors.
=> chore: contextualise process loop error logging

README.md
=> chore: include configuration warning

README.md
Fix pigeon config.yaml for arbitrum
=> fix arb-main to arbitrum-main

README.md
=> Add BLAST to README

README.md
fixes https://github.com/VolumeFi/paloma/issues/1480
=> Update setup instruction for tumbler

README.md, go.mod, go.sum
Updates the Paloma dependencies and prepares README for release. Lots of whitespace linting as well.
=> chore: update Paloma dependency

.github/workflows/ci-test.yml
Switch to GoTestSum for CI test runs.
=> ci: use gotestsum

.github/workflows/ci-test.yml
This change fixes the GH runners.
=> ci: fix test runners

chain/evm/compass.go, chain/evm/compass_test.go
- https://github.com/VolumeFi/paloma/issues/1037
Previously, if we failed to get the balance for a single validator, we would return an error for the whole response. Now, we return empty balances for those that failed, instead. If we fail to get all of them, we return an error.
This will allow us to jail validators with consistently missing balances.
=> chore: return empty balance on evidence error

README.md
Update README to latest (upcoming) release.
=> chore: update version in README

chain/evm/compass.go
https://github.com/VolumeFi/paloma/issues/1867
This change updates the Paloma address representation from `string` to `bytes32` in the compass contract.
=> chore: refactor paloma address to bytes32

README.md
=> chore: update readme to v2.1.0

README.md
=> chore: update README to v2.2.1

README.md
=> chore: update README to v2.2.2

util/ion/tx.go
- https://github.com/palomachain/paloma/issues/1305
Make sure pigeon txs to paloma have enough gas.
=> fix: add gas adjustment parameter to paloma txs

README.md
=> chore: update README to v2.3.2

README.md, chain/evm/compass.go
=> fix: nil pointer exception

README.md
increase the gas adjustment to 10.0 in the README for pigeon config.yaml
=> update gas adjustment to 10.0
