palomachain/pigeon

Dockerfile, config/config.go
- https://github.com/palomachain/paloma/issues/85
Sometimes it's easier to inject certain values through the env variables. This PR makes it possible to write the env variable in the config and it would read the value from it.
=> Read env variables from within the config

.gitattributes, client/paloma/client.go, client/paloma/client_test.go, proto/paloma/consensus/query.proto, types/paloma/x/consensus/types/mocks/QueryServer.go, types/paloma/x/consensus/types/query.pb.go
- https://github.com/palomachain/paloma/issues/83
Once messages have reached a consensus on the chain side, we need to fetch them. This PR queries the chain to get those messages. The proto files were copied from paloma chain to support the new query params.
=> Query messages that have reached consensus

app/app.go, attest/attest.go, client/paloma/client.go, go.mod, go.sum, relayer/relayer.go, relayer/sign_messages_for_execution.go
- https://github.com/palomachain/paloma/issues/106
We need to made it possible for sparrow to attest to events from _"outside"_ world. This is a generic solution which allows us to do just that.
- ensured that tests are working
=> Generic attesting to events from sparrow

README.md
- Solves no issues
Add service file for pigeond
=> add service file for pigeond

.gitignore, app/app.go, chain/evm/client.go, chain/evm/client_test.go, chain/evm/compass.go, chain/evm/errors.go, cmd/pigeon/main.go, go.mod, go.sum, relayer/process.go, util/slice/reverse.go
- https://github.com/palomachain/paloma/issues/341
- https://github.com/palomachain/paloma/issues/338
There was a bug where pigeon was querying the valset by the provided starting height of a supported chain, while valset can only be added **after** the fact that we have added a support for a new chain.
=> Fix issue where pigeon is unable to fetch the right valset_id

README.md
New chain to address upgrade to fix validator jailing issue around pigeon balances.
Update the README with the new chain id, paloma-testnet-7
None as yet. Will verify with new network.
=> update chain-id to paloma-testnet-7 for new chain

cmd/pigeon/cmd_evm.go
- https://github.com/palomachain/paloma/issues/406
Now it's possible to export keys created by pigeon.
=> Exporting private key

README.md
N/A
pigeon config.yaml still references `keyring-type: test` updating to `keyring-type: os`
Currently live.
=> Update keyring-type to os

chain/evm/client.go, chain/evm/health_check.go, cmd/pigeon/cmd_health_check_verify.go, config.example.yaml, health/background_check.go, health/interface.go, relayer/health_check.go, relayer/process.go
Check if new chains are properly configured.
=> Add healtchecks which do not depend on the paloma running

README.md
This is an update to support Binance Smart Chain in the pigeon README.
This is an update to support Binance Smart Chain in the pigeon readme so that new installs will support Binance Smart Chain relay service.
=> Pigeon readme update supported chains

.mergify.yml, CHANGELOG.md, CONTRIBUTING.md
Copies changes from pigeon for releasing and changelog.
Also, I have backporting commented out because Pigeon's release cadence and versions seem to be too chaotic to use at the moment.
=> chore: release infra

chain/evm/client.go, chain/evm/compass.go, chain/evm/mock_evmClienter_test.go
https://github.com/VolumeFi/paloma/issues/8
- fix wrong function name.
- fix weird boolean returns.
- call `isArbitraryCallAlreadyExecuted()` function only once with maximum fetch block length(9999).
=> fix fetch event bug

.goreleaser.yaml
n/a
On the machine from 2019-2020 the Pigeon binary can not be launched, however Paloma can.
=> removed amd64-v3 demand from goreleaser config

chain/paloma/wrappers.go
It occurred to me that if we had a message come in 9 seconds after the previous, we wouldn't get the desired 10 second spread between messages. Moving the sleep fixes this
=> Moving sleep to before sending a message

.goreleaser.yaml
The crux of this issue is that the version of glibc on the github machine that builds this vs that of those who run it may be different. We need to use this env variables build in the libraries instead of dynamically loading them on the host machine at runtime.
=> Fix GLIBC errors seen by some

Makefile, README.md
The crux of this issue is that the version of glibc on the github machine that builds this vs that of those who run it may be different. Until this is fixed, we need to add instructions for people to build this on their own machine
=> Add build instructions to readme and fix build version

go.mod, go.sum
Keeping mods up to date.
* ibc-go needed a security patch: https://forum.cosmos.network/t/ibc-security-advisory-huckleberry/10731
* gomega was suggested by dependabot
* testify was suggested by dependabot
- I tested this on a local testnet without issue.
=> Keeping mods up to date

relayer/process.go, relayer/start.go
Closes https://github.com/VolumeFi/paloma/issues/268
This is in response to some behavior we saw when there were lots of messages in the queue.  They were being very slowly churned through and we didn't understand why.  Here's what was happening:
When pigeon runs process, it's doing three things.
1. Sign messages
2. Relay messages
3. Provide evidence for messages
We thought that failing jobs weren't getting deleted from the queue, but they actually do if Pigeon is able to report back regularly that it tried relaying and failed.
The problem is, Pigeon was getting stuck at relaying messages and hanging too long.  It would then return an error and never get to the step where it provides evidence.  That is, until there were no more messages left that needed relayed.  This is why we saw a very …
=> Fix and refactor some process logic

chain/paloma/wrappers.go, relayer/start.go
- https://github.com/VolumeFi/paloma/issues/299
Remove the sleep.  After some testing, it appears that previous changes
have fixed the account sequence mismatch errors.  Pigeon still needs the
locks in place so that it doesn't run over itself, but as long as one
message is in flight at a time, there are no more errors with account
sequence mismatch
One caveat to this.  If another actor uses the validator account key, we will
still see account sequence mismatch errors.  The validator account key needs to
belong solely to Pigeon
=> Ticking every 10 seconds for faster processing of new messages

relayer/start.go
- https://github.com/VolumeFi/paloma/issues/299
We arbitrarily chose 10 seconds as a baseline for more speed.  There's no reason we can't go faster though.  State is only committed each block (~5.6s), but if we loop faster, we have a good chance of picking up work from the current block and submitting it in the very next block.
=> Loop every second

chain/errors.go, relayer/relayer.go, relayer/start.go
- Needed because of https://github.com/VolumeFi/paloma/issues/299
Previously, this was only checked at startup.  The problem is, pigeons get jailed all the time while they're still running.  The check is never re-checked and the pigeon keeps trying to send messages to Paloma that will just be rejected.  This becomes more of a problem now that we're looping much faster and sending more messages.
Now, we check in with Paloma every 5 seconds to make sure our pigeon is still staking.  If it's not staking, it doesn't bother trying to do work that will just be rejected.
The one exception to this is the keep_alive.  We so aggressively jail pigeons that I don't want anything delaying a keep_alive message.  We can fire them off and let them fail when jailed.
=> Continue checking if a pigeon is staking

go.mod, go.sum
We were previously pointing to a commit of paloma in order to get the latest changes.  Now there's a new release, so let's point to that.  These are equivalent in functionality
=> Upgrade to paloma v1.3.0

Dockerfile
This has already been merged into the release branch, but we need it in master as well.  Here's the master PR.
The release was broken due to the most recent upgraded dependencies.  We were getting this error:
```
/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.3/types/address.go:88:26: undefined: atomic.Bool
note: module requires Go 1.19
/go/pkg/mod/github.com/ethereum/go-ethereum@v1.12.0/metrics/counter.go:118:15: undefined: atomic.Int64
/go/pkg/mod/github.com/ethereum/go-ethereum@v1.12.0/metrics/counter_float64.go:119:19: undefined: atomic.Uint64
/go/pkg/mod/github.com/ethereum/go-ethereum@v1.12.0/metrics/counter_float64.go:147:35: undefined: atomic.Uint64
/go/pkg/mod/github.com/ethereum/go-ethereum@v1.12.0/metrics/ewma.go:78:19: undefined: atomic.Int64 …
```
=> Upgrade release script to go 1.20

go.mod, go.sum
This was subbed in up to now because we didn't have a new paloma release yet.  Now we do.
=> Update mod file to point at newly published paloma version

chain/evm/deploy_contract.go
This output looks like it was put in a long time ago while debugging.  It's not using the log package, and it doesn't look like useful information to log.  Removing it to clean up our logs a bit.
=> Removing unnecessary output in logs using Println

chain/evm/processor.go
- https://github.com/VolumeFi/paloma/issues/478
Kava uses tendermint hashes for all of its block hashes, which results in problems when trying to recalculate them automatically.
Until we have proper support for parallel EVM client implementations, we're going to add a hack which circumvents the actual block hash recalculation in case the target chain is kava-main
=> hack: support kava-main

.goreleaser.yaml
We also had this in Paloma.  It was fixed there, but we forgot to fix it here.  This affects the naming convention of the release files.
=> Fixing typo in goreleaser

README.md
Update Docs for Tx type 2 chains for gas adjustments.
N/A
N/A
=> update for tx-type 2 chains with note in docs

app/app.go
- https://github.com/VolumeFi/paloma/issues/573
Package semver implements comparison of semantic version strings. In this package, semantic version strings must begin with a leading "v", as in "v1.0.0". Our current keep-alive implementation fails if the version is not prefixed with a `v`.
=> fix: 🔧 Ensure v-prefixed version report

chain/evm/processor.go
This is an emergency patch for a broken mainnet.  I will test it on our mainnet node before requesting a merge.
=> Extend the kava hack to another block height

relayer/build_processors.go
- https://github.com/palomachain/paloma/issues/938
- https://github.com/palomachain/paloma/issues/939
This is needed because some validators are getting errors building processors, but the errors don't tell which chain was the problem.  Now the errors include that information
=> Add more verbose logging to building processors

app/app.go, chain/paloma/client.go, cmd/pigeon/cmd_start.go, config/config.go, go.mod, go.sum, internal/mev/blxr/client.go, internal/mev/blxr/client_test.go, internal/mev/blxr/health.go, internal/mev/blxr/health_test.go, internal/mev/client.go, internal/traits/traits.go, relayer/relayer.go, relayer/start.go, relayer/update_valset.go
- https://github.com/VolumeFi/paloma/issues/619
This change introduces a few new additions, namely:
- Pigeon traits: an arbitrary set of capabilities for EVM chains which may be listed per chain and will be stored as part of the active valset on chain
- MEV relaying: scaffolding the possibility to relay messages via MEV endpoints if properly setup in the configuration
- BLXR client: the first (and currently only) implementation of MEV relaying. It's still missing the relay implementation, but everything else is there
The change also includes some housekeeping and directory changes. I was hoping to move towards `pkg/internal` and `pkg/app`, but we won't be able to properly import while other packages remain on the root level, so this will have to do for now.
=> feat: add blxr client and pigeon trait

relayer/start.go
- https://github.com/VolumeFi/paloma/issues/640
Paloma's block time is decreasing significantly.  It now makes sense to run pigeon signing, relaying, and attesting at sub-second intervals.
=> Speed up pigeons where useful

chain/evm/compass.go, chain/evm/compass_test.go
- https://github.com/VolumeFi/paloma/issues/673
Pigeon has been testing the validator power against a hard coded number instead of looking for 2/3 consensus of the power of the valset.  This is incorrect and can result in Pigeon incorrectly believing consensus is achieved or not.
If consensus is not achieved, pigeon will end up sending messages that will fail.  If consensus is achieved but pigeon believes otherwise, Pigeon won't send messages that would succeed.
Now, we're comparing the signed power vs the valset power.  This should be the correct way of checking consensus.
=> Fix pigeon consensus calculation

app/app.go, cmd/pigeon/cmd_start.go, config.example.yaml, config/config.go, health/server.go, internal/mev/client.go, relayer/build_processors.go, relayer/build_processors_test.go, relayer/health_check.go, relayer/health_check_test.go, relayer/message_attester_test.go, relayer/message_relayer_test.go, relayer/message_signer_test.go, relayer/relayer.go
- https://github.com/VolumeFi/paloma/issues/745
This change adds a new configuration field for server health server address binding. It also contains some minor housekeeping chores.
=> feat: #745 add health server address binding config

relayer/heartbeat/cache.go, relayer/heartbeat/cache_test.go, relayer/heartbeat/heartbeat.go, relayer/start.go
- https://github.com/palomachain/paloma/issues/973
This introduces some additional logging around sending keep alive calls. The most important change is the forced cache invalidation after a successful keep-alive call to Paloma in order to avoid unneeded calls.
=> Force keep-alive cache invalidation

relayer/start.go
- https://github.com/palomachain/paloma/issues/976
This was previously checking every 5 seconds for events to send a token to Paloma.  This may be unnecessarily using up RPC calls for pigeons when not much is happening.  Slowing this down, which will effectively reduce the call numbers while batching events that may happen together.
Also removed an unused interval accidentally left in
=> Slow down evm event checking

chain/evm/compass.go, chain/evm/compass_test.go
- https://github.com/VolumeFi/paloma/issues/782
I'm not actually sure how this hasn't been broken for a much longer time.  When checking if a logic call was already executed, the filter topic is returning other logic calls with different IDs.  The current check of "are they any?" isn't sufficient.
Now, we are going through the returned logs and comparing the message ID of the log to the current message ID
=> Better logic for checking for executed messages

relayer/heartbeat/cache.go, relayer/heartbeat/cache_test.go
- https://github.com/VolumeFi/paloma/issues/794
We check every 30 blocks, not seconds. How does Pigeon know when 30 blocks are due? By estimating the block speed. How does it know the block speed? By comparing block heights when refreshing its cache. So if we get a very low height difference of blocks right after a halt, Pigeons won't be calling in for a good while, as they think the chain is moving very slowly now (which it isn't).
This change adds some thresholds to both, the last cache refresh time delta, and the last block height delta. In case either of them is hit, we simply work with the default values.
Side effect: eventually, this will also trigger Pigeons to keep aggressively unjailing during a chain halt, so once we start moving again, their TTL will be refreshed.
=> feat: prevent unrealistic estimates during chain halt

chain/evm/processor.go, relayer/build_processors.go, relayer/relayer.go, relayer/update_valset.go
I'm surprised this hasn't flared up before. Pigeons will usually "build processors" before every operation, meaning they will ask Paloma for the latest chain configuration and compare their local setup. In case there's a difference, they will rebuild their local setup to match what's asked for by Paloma. 
The code for this was not written with concurrency in mind, but is part of most of our background tasks which all run concurrently. Therefore, updating the internal state would interfere with each other, leading to contradicting results, a ton of update calls, invalid and incomplete data in the valsets and more.
This change adds a read/write mutual exclusion lock around the code in question, ensuring that reads stay performant, but don't interfere with updating the internal state any …
=> fix: avoid race condition when building chain processors

relayer/heartbeat/heartbeat.go, relayer/start.go
I thought I had done this one earlier, but it seems the changes from my branch never went on to master. This will help with the jailing of pigeons who starve while waiting for the lock, but it will increase the amount of `incorrect account sequence` errors we'll see. This should be addressed with operator keys sooner rather than later.
=> fix: remove keep alive mutex locking

chain/evm/compass.go, chain/evm/compass_test.go, chain/evm/errors.go, cmd/pigeon/cmd_evm.go
This change primarily targets the `SubmitLogicCall` handler, returning an error in case a message matching the current message ID is already found on the target chain. This error will now be added to the `error data` of the message, instructing Paloma to clear it from the queue. It might still be retried once with a different pigeon, but not clog the queue for 45 minutes.
=> fix: avoid retries on already executed messages

chain/paloma/client.go
This change adds some filtering when querying messages from Paloma, which by default will not be filtered by chain ID.
I don't know why this wasn't part of the original change that added the gravity stuff, I imagine it was simply overlooked. I tried to add some test coverage as well, but I find the current solution to be more than lacking. We define the protobuf stuff in Paloma, then we also generate the mocks there. There's no automation or `go:generate` for this, and most packages don't even include mocks for the protobuf parts.
So, even going ahead manually creating the mocks in Paloma, pushing the changes, updating the references in Pigeon and writing a test against it, there is 0 guarantee that a future dev (or me) will make changes to the proto definitions and simply not update the …
=> fix: filter gravity batches queried from paloma

app/app.go, relayer/heartbeat/heartbeat.go
- https://github.com/VolumeFi/paloma/issues/856
This brings back locking when making calls to keep alive. In order to prevent a jailing due to sometimes very long waiting times to acquire the lock (> 1 minute), we start calling 15 minutes before the new TTL (approx 1 hr) runs out.
=> chore: re-introduce locking

README.md, chain/evm/compass.go, go.mod, go.sum
- https://github.com/VolumeFi/paloma/issues/795
This includes the scaffolding for the full erc20 ownership transfer. We're pushing this out as an intermediate solution to prevent the chain from getting stuck in a deployment loop. The remaining work will be to actually call the old compass, verifying that the TX was executed properly before reporting on the outcome.
=> Prework: gravity compass upgrade

app/app.go
To be honest, I'm not 100% sure whether this is still needed, as it seems to work fine without. But other messages are registered here, and according to
https://github.com/strangelove-ventures/lens/issues/300, some codecs might be missing without.
Tested in private test net.
=> fix: missing message iface registration

chain/evm/compass.go, chain/evm/compass_test.go
- https://github.com/VolumeFi/paloma/issues/855
There's actually no reason to return an error in case we have a valset mismatch. We just log the matter and stop processing of the message until the next loop. It's cleaner, more cost efficient and reliable.
=> fix: don't return an error

chain/evm/compass.go
- https://github.com/VolumeFi/paloma/issues/880
Looks like there was a bug in the gravity code that would loop over all log events on the target chain for the past 9999 blocks, but would not exit the loop if it found a match, overriding its results in the process and therefore always failing to notice the already processed message.
=> fix: prevent gravity batches being resubmitted indefinitely

app/app.go
- https://github.com/VolumeFi/paloma/issues/939
- https://github.com/VolumeFi/paloma/issues/895
We have a gravity batch stuck that is being relayed over and over again every 10000 blocks. Pigeon actually see the event on the target chain, but fail to inform Paloma because the gravity messages hadn't been registered against the `sdk.Msg` interface. 
This was most likely just forgotten in the bulk of work for gravity. What bothers me is that this happened before with the `AddStatusUpdate` message, and apparently for some nodes this works just fine, while for others it doesn't and leads to a crash. Definitely needs more understanding. Either the type is registered or it isn't, and if it isn't, it should fail deterministically across all nodes. But it doesn't.
Tested in private test net, this …
=> fix: missing interface registrations

chain/evm/compass.go
Before we get around to supporting https://github.com/VolumeFi/paloma/issues/875, we simply kept track of the transaction hash of the original contract upload. However, only the original relaying validator actually kept a reference to this transaction.
So, unless you got selected to relay both the original smart contract as well as the follow-up call to relink the token ownership, you wouldn't have a copy of that hash, meaning you wouldn't be able to attest to the original message.
This change simply creates a reference to the last TX that was attested on each target chain. Since we only verify that the TX in question is present on the target chain, and the ERC20 token relink does not happen after a successful contract deployment, this should be all that's needed to allow Pigeons to …
=> hack: erc20 relink: store original contract upload tx

README.md, go.mod, go.sum
Update README and link to released version of Paloma.
=> chore: prepare v1.10.0

README.md, chain/paloma/client.go
The new validator key config wasn't used throughout the project. This fixes the issue and also adapts the documentation to how it needs to be when creating new signing keys for pigeon.
=> fix: validator key not being used

chain/evm/client.go, chain/evm/client_test.go, chain/evm/errors.go
- https://github.com/VolumeFi/paloma/issues/988
We see a lot of error logs when trying to verify validators balances on chains. This is because the established architecture allows to query at arbitrary times, even though Paloma always only uses the current time. The algorithm used to identify the closest block to the given time can lead to resulting in the latest block number, which might not be finalised yet. 
For now, we just fall back to the `latest block number - 1` in this case, which should work. In the future, we might want to strip out the entire block height search and always use the current block height, as it's using binary search to approximate the block and makes a decent amount of API calls while doing so.
=> fix: avoid overly eager balance lookup

chain/evm/compass.go, internal/ethfilter/ethfilter.go, internal/ethfilter/ethfilter_test.go
- https://github.com/VolumeFi/paloma/issues/1023
Introduces some standardisation towards querying target chain event data, ensuring we do not query into the future.
=> fix: block lockup range error

README.md
=> fix gas-adjustment, add blast

chain/evm/client.go
- https://github.com/VolumeFi/paloma/issues/1488
This error is ejected directly from the `geth` package before the transaction is even sent to the RPC. I'm not entirely sure why we're seeing this error on main net, as parameters should always be populated as necessary by default. This change adds some explicit statements to `nil` out any fields which may not coexist as part of the transaction options.
=> fix: invalid gas arg combination

chain/evm/client.go, chain/evm/compass.go, go.mod, go.sum
- https://github.com/VolumeFi/paloma/issues/1501
The error `both gasPrice and (maxFeePerGas or maxPriorityFeePerGas) specified` actually happens during gas estimation, and is **not** emitted from the `op-geth` framework. Because it's possible to encounter the **exact same error** in the framework as well, we got led astray.
This change fixes the gas estimation in a way that should force all `tx type 2` chains to omit the gas price entirely when making the call.
=> fix: gas estimation error

chain/paloma/gravity.go, chain/paloma/wrappers.go, util/ion/broadcast.go, util/ion/tx.go
The gRPC message sender implementation for gravity was never properly updated to work with multiple signing keys in Pigeon. This change adds the necessary changes to ensure all messages are sent with fee grant in mind.
=> fix: gravity gRPC client implementation

.github/workflows/ci-test.yml, .golangci.yml, Dockerfile, chain/evm/compass.go, go.mod
- https://github.com/palomachain/paloma/issues/1165
I actually wrote up a new package that would concurrently query through multiple search windows, but I think this simple approach is more rigid, and although it will take Pigeons some time to catch up with this, at least we can be pretty sure they actually will eventually be caught up and riding the edge again.
=> feat: limit query window

chain/evm/client.go, chain/evm/client_test.go
- https://github.com/VolumeFi/paloma/issues/1639#event-13005610845
> We found some transactions can fail if we don't provide gas enough.
> https://github.com/VolumeFi/pigeon/blob/e67c743dc9bace0b755d8460750c4e608d80d5c5/chain/evm/client.go#L352
> I suggest multiplication by >=1.3 instead 1.2.
> 1.5 will be good enough.
=> chore: increase gas limit multiplier to 1.5f

chain/paloma/wrappers.go
- Closes https://github.com/VolumeFi/paloma/issues/1705
The logger was trying to marshal `MsgAddEvidence` messages as JSON, but failing on the `Any` fields, as it does not have access to the unpacker interfaces registry.
=> fix: failed to marshal JSON for types.Any

chain/evm/compass.go, go.mod, go.sum
- Closes https://github.com/VolumeFi/paloma/issues/1848
Skyway needs to know the compass ID that generated the turnstone messages, this PR adds it to all messages.
Replaces https://github.com/palomachain/pigeon/pull/417
=> feat: add compass ID to all turnstone messages

chain/evm/client.go, chain/evm/compass.go, chain/evm/compass_test.go, chain/evm/errors.go, chain/evm/mock_ethClientConn_test.go, chain/evm/mock_evmClienter_test.go, go.mod, go.sum
- https://github.com/VolumeFi/paloma/issues/159
Pigeon changes to the new feature in paloma on https://github.com/palomachain/paloma/pull/1200
- pigeons receives the new turnstone message type and calls the necessary function on compass
- When adding evidence, pigeon retrieves the transaction receipt and adds is as well
- The receipt contains the event that contains the new contract address
=> feat: deploy user smart contracts

chain/evm/client.go, chain/evm/client_test.go, chain/evm/compass.go, chain/evm/compass_test.go, chain/evm/mocks/CompassBinding.go, chain/evm/mocks/PalomaClienter.go
- https://github.com/VolumeFi/paloma/issues/2089
- https://github.com/VolumeFi/paloma/issues/2094
- https://github.com/VolumeFi/paloma/issues/2128
This change addresses the inflated estimate that used to include the `1.5` modifier applied to the limit in order to ensure inclusion in the next tx. Since most of this won't actually be consumed, we now only return the pure, raw estimate retrieved from the RPC.
There's also a bug fix in this, addressing an edge case where the external address resolving of the assignee would fail in case they were jailed during the last published snapshot.
=> feat: improve gas estimation

chain/evm/compass.go, chain/evm/compass_test.go
- https://github.com/VolumeFi/paloma/issues/2095
Add transaction receipts to all turnstone message proofs. The receipts will be needed in paloma to attest the txs were successful.
=> chore: add receipts to all turnstone tx proofs

chain/evm/client.go, chain/evm/compass.go, chain/evm/mocks/PalomaClienter.go, chain/paloma/query.go, go.mod, go.sum
- https://github.com/VolumeFi/paloma/issues/2160
Query Paloma for blocks to check for skyway events.
Depends on https://github.com/palomachain/paloma/pull/1289. `go.mod` needs to be updated after paloma's PR is merged.
=> feat: query skyway query unobserved blocks

chain/evm/compass.go, chain/evm/compass_test.go
- Closes https://github.com/VolumeFi/paloma/issues/2191
Currently some errors do not set ErrorData on turnstone messages. When there's an error on these messages (for instance an RPC error) they just stay on the queue until they expire.
We want all errors to set the ErrorData on messages so they can fail fast and be retried. Furthermore, compass errors are treated as normal errors and returned in the ErrorData as well.
=> fix: set ErrorData on all errors from handling a turnstone message

relayer/errors.go, relayer/message_attester.go, relayer/message_estimator.go, relayer/message_relayer.go, relayer/message_signer.go
- https://github.com/VolumeFi/paloma/issues/2201
Paloma validators are getting jailed too often. One of the causes is if there is an issue on one chain, and pigeons fail to attest message on it, they won't try to attest messages on other chains. This can result in additional jailings after some instability on a chain or RPC provider.
=> chore: continue message processing after error

chain/evm/compass.go
- Closes https://github.com/VolumeFi/paloma/issues/2199
The base chain was having some issues and was reporting a current block height lower than what we had already processed. We now check for that condition.
Also improved logging to have a better understanding of the request that failed.
=> fix: check from and to fields on log filters

chain/evm/client.go, chain/evm/client_test.go
- https://github.com/VolumeFi/paloma/issues/2299
This change adds an additional 100k gas buffer to cover the cost of bootstrapping ops on Compass.
=> chore: [#2299] Gas buffer covering compass bootstrap

.github/workflows/ci-test.yml, .github/workflows/release.yml, .golangci.yml, Dockerfile, Makefile, README.md, chain/evm/deploy_contract.go, go.mod, internal/mev/blxr/relay.go, util/ion/tx.go
- https://github.com/VolumeFi/paloma/issues/2540
- Lock the CI runner versions
- Upgrade to the latest released version of Go
=> ci: increase Go version

.golangci.yml, relayer/build_processors.go, relayer/message_attester_test.go, relayer/message_relayer_test.go, relayer/message_signer_test.go
- https://github.com/VolumeFi/paloma/issues/2727
> [!warning]
> 🛠️ This new approach changes the entire concept of how Pigeon is designed, I have no idea on the consequences and it might make everything a lot worse. Treat with care.
This change introduces support to keep Pigeon running even with partial chain support. The downside is that Pigeons which only want to support a subset of the external chains may now freely do so without getting punished.
=> feat: experimental support for selective chain relays !breaking

.golangci.yml, relayer/build_processors.go, relayer/message_attester_test.go, relayer/message_relayer_test.go, relayer/message_signer_test.go
Reverts palomachain/pigeon#454
With https://github.com/palomachain/pigeon/pull/455 merged, this is no longer required and should not be rolled out to avoid further instability.
=> Revert "feat: experimental support for selective chain relays !breaking"
